/** Maps country names (and common aliases) to their continent. */
export const countryToContinentMap: Record<string, string> = {
  // ── North America ──
  'United States': 'North America',
  'USA': 'North America',
  'US': 'North America',
  'Canada': 'North America',
  'Mexico': 'North America',
  'Guatemala': 'North America',
  'Cuba': 'North America',
  'Haiti': 'North America',
  'Dominican Republic': 'North America',
  'Honduras': 'North America',
  'Nicaragua': 'North America',
  'El Salvador': 'North America',
  'Costa Rica': 'North America',
  'Panama': 'North America',
  'Jamaica': 'North America',
  'Trinidad and Tobago': 'North America',
  'Belize': 'North America',
  'Bahamas': 'North America',
  'Barbados': 'North America',
  'Puerto Rico': 'North America',
  'Bermuda': 'North America',

  // ── South America ──
  'Brazil': 'South America',
  'Colombia': 'South America',
  'Argentina': 'South America',
  'Peru': 'South America',
  'Venezuela': 'South America',
  'Chile': 'South America',
  'Ecuador': 'South America',
  'Bolivia': 'South America',
  'Paraguay': 'South America',
  'Uruguay': 'South America',
  'Guyana': 'South America',
  'Suriname': 'South America',

  // ── Europe ──
  'United Kingdom': 'Europe',
  'UK': 'Europe',
  'England': 'Europe',
  'Scotland': 'Europe',
  'Wales': 'Europe',
  'France': 'Europe',
  'Germany': 'Europe',
  'Italy': 'Europe',
  'Spain': 'Europe',
  'Portugal': 'Europe',
  'Netherlands': 'Europe',
  'Holland': 'Europe',
  'Belgium': 'Europe',
  'Switzerland': 'Europe',
  'Austria': 'Europe',
  'Sweden': 'Europe',
  'Norway': 'Europe',
  'Denmark': 'Europe',
  'Finland': 'Europe',
  'Ireland': 'Europe',
  'Poland': 'Europe',
  'Czech Republic': 'Europe',
  'Czechia': 'Europe',
  'Romania': 'Europe',
  'Hungary': 'Europe',
  'Greece': 'Europe',
  'Croatia': 'Europe',
  'Serbia': 'Europe',
  'Bulgaria': 'Europe',
  'Slovakia': 'Europe',
  'Slovenia': 'Europe',
  'Lithuania': 'Europe',
  'Latvia': 'Europe',
  'Estonia': 'Europe',
  'Iceland': 'Europe',
  'Luxembourg': 'Europe',
  'Malta': 'Europe',
  'Cyprus': 'Europe',
  'Albania': 'Europe',
  'North Macedonia': 'Europe',
  'Montenegro': 'Europe',
  'Bosnia and Herzegovina': 'Europe',
  'Moldova': 'Europe',
  'Ukraine': 'Europe',
  'Belarus': 'Europe',
  'Monaco': 'Europe',
  'Andorra': 'Europe',
  'Liechtenstein': 'Europe',
  'San Marino': 'Europe',

  // ── Africa ──
  'Nigeria': 'Africa',
  'Ethiopia': 'Africa',
  'Egypt': 'Africa',
  'South Africa': 'Africa',
  'Kenya': 'Africa',
  'Tanzania': 'Africa',
  'Uganda': 'Africa',
  'Algeria': 'Africa',
  'Sudan': 'Africa',
  'Morocco': 'Africa',
  'Ghana': 'Africa',
  'Mozambique': 'Africa',
  'Madagascar': 'Africa',
  'Cameroon': 'Africa',
  'Ivory Coast': 'Africa',
  "Côte d'Ivoire": 'Africa',
  'Niger': 'Africa',
  'Burkina Faso': 'Africa',
  'Mali': 'Africa',
  'Malawi': 'Africa',
  'Zambia': 'Africa',
  'Senegal': 'Africa',
  'Chad': 'Africa',
  'Somalia': 'Africa',
  'Zimbabwe': 'Africa',
  'Rwanda': 'Africa',
  'Benin': 'Africa',
  'Tunisia': 'Africa',
  'Togo': 'Africa',
  'Sierra Leone': 'Africa',
  'Libya': 'Africa',
  'Congo': 'Africa',
  'Liberia': 'Africa',
  'Mauritania': 'Africa',
  'Eritrea': 'Africa',
  'Namibia': 'Africa',
  'Gambia': 'Africa',
  'Botswana': 'Africa',
  'Gabon': 'Africa',
  'Lesotho': 'Africa',
  'Guinea': 'Africa',
  'Mauritius': 'Africa',
  'Eswatini': 'Africa',
  'Djibouti': 'Africa',
  'Cape Verde': 'Africa',
  'Seychelles': 'Africa',

  // ── Asia ──
  'China': 'Asia',
  'India': 'Asia',
  'Indonesia': 'Asia',
  'Pakistan': 'Asia',
  'Bangladesh': 'Asia',
  'Japan': 'Asia',
  'Philippines': 'Asia',
  'Vietnam': 'Asia',
  'Turkey': 'Asia',
  'Iran': 'Asia',
  'Thailand': 'Asia',
  'Myanmar': 'Asia',
  'South Korea': 'Asia',
  'Korea': 'Asia',
  'Iraq': 'Asia',
  'Afghanistan': 'Asia',
  'Saudi Arabia': 'Asia',
  'Uzbekistan': 'Asia',
  'Malaysia': 'Asia',
  'Nepal': 'Asia',
  'Yemen': 'Asia',
  'North Korea': 'Asia',
  'Sri Lanka': 'Asia',
  'Kazakhstan': 'Asia',
  'Syria': 'Asia',
  'Cambodia': 'Asia',
  'Jordan': 'Asia',
  'Azerbaijan': 'Asia',
  'United Arab Emirates': 'Asia',
  'UAE': 'Asia',
  'Tajikistan': 'Asia',
  'Israel': 'Asia',
  'Laos': 'Asia',
  'Lebanon': 'Asia',
  'Kyrgyzstan': 'Asia',
  'Turkmenistan': 'Asia',
  'Singapore': 'Asia',
  'Oman': 'Asia',
  'Palestine': 'Asia',
  'Kuwait': 'Asia',
  'Georgia': 'Asia',
  'Mongolia': 'Asia',
  'Armenia': 'Asia',
  'Qatar': 'Asia',
  'Bahrain': 'Asia',
  'Taiwan': 'Asia',
  'Hong Kong': 'Asia',
  'Macao': 'Asia',
  'Macau': 'Asia',
  'Maldives': 'Asia',
  'Bhutan': 'Asia',
  'Brunei': 'Asia',
  'Russia': 'Asia',

  // ── Oceania ──
  'Australia': 'Oceania',
  'New Zealand': 'Oceania',
  'Papua New Guinea': 'Oceania',
  'Fiji': 'Oceania',
  'Solomon Islands': 'Oceania',
  'Vanuatu': 'Oceania',
  'Samoa': 'Oceania',
  'Tonga': 'Oceania',
  'Micronesia': 'Oceania',
  'Palau': 'Oceania',
  'Marshall Islands': 'Oceania',
  'Kiribati': 'Oceania',
  'Tuvalu': 'Oceania',
  'Nauru': 'Oceania',
  'Guam': 'Oceania',
  'French Polynesia': 'Oceania',
  'New Caledonia': 'Oceania',
  'Hawaii': 'Oceania',
};
